import React from 'react';
import ReactMarkdown from 'react-markdown';
import { Message as MessageType } from '../../types/conversation';
import { parseContent, formatTimestamp, formatLLMMetadata } from '../../utils/conversationUtils';

interface MessageProps {
  message: MessageType;
  index: number;
  showThinking: boolean;
  onToggleThinking: (messageId: string) => void;
  onRetry?: (messageId: string) => void;
  isRetrying?: boolean;
}

const Message: React.FC<MessageProps> = ({
  message,
  index,
  showThinking,
  onToggleThinking,
  onRetry,
  isRetrying
}) => {
  const parsedContent = parseContent(message.content);
  const metadataText = formatLLMMetadata(message.llm_metadata, message.llm_id);

  return (
    <div key={message.message_id} className={`message ${message.role}`}>
      <div className="message-header">
        <span className="message-role">
          {message.role === 'user' ? 'You' : 
           message.role === 'assistant' ? 'Assistant' : 'System'}
        </span>
        <span className="message-timestamp">
          {formatTimestamp(message.timestamp)}
        </span>
      </div>
      
      {/* Thinking toggle for assistant messages with thinking content */}
      {message.role === 'assistant' && parsedContent.hasThinking && (
        <div className="thinking-toggle">
          <button 
            className="thinking-toggle-btn"
            onClick={() => onToggleThinking(message.message_id)}
            aria-label={showThinking ? "Hide thinking process" : "Show thinking process"}
          >
            <span className={`toggle-arrow ${showThinking ? 'expanded' : ''}`}>▼</span>
            {showThinking ? 'Hide' : 'Show'} thinking process
          </button>
        </div>
      )}

      {/* Thinking content (conditionally visible) */}
      {message.role === 'assistant' && parsedContent.hasThinking && showThinking && (
        <div className="thinking-content">
          <div className="thinking-header">
            <span>💭 Thinking Process</span>
          </div>
          {parsedContent.thinking.map((think, idx) => (
            <div key={idx} className="thinking-block">
              {think}
            </div>
          ))}
        </div>
      )}

      {/* Main message content */}
      <div className="message-content">
        {message.role === 'assistant' ? (
          <ReactMarkdown>{parsedContent.cleanContent}</ReactMarkdown>
        ) : (
          parsedContent.cleanContent
        )}
      </div>

      {/* Retry button for assistant messages */}
      {message.role === 'assistant' && onRetry && (
        <div className="message-actions">
          <button 
            className="retry-btn"
            onClick={() => onRetry(message.message_id)}
            disabled={isRetrying}
            aria-label="Retry generating this response"
          >
            {isRetrying ? (
              <>
                <span className="retry-spinner">⟳</span>
                Retrying...
              </>
            ) : (
              <>
                <span className="retry-icon">↻</span>
                Retry
              </>
            )}
          </button>
        </div>
      )}

      {/* Enhanced metadata */}
      {(message.llm_id || metadataText) && (
        <div className="message-metadata">
          {metadataText ? (
            <small>{metadataText}</small>
          ) : (
            <small>Generated by: {message.llm_id}</small>
          )}
        </div>
      )}
    </div>
  );
};

export default Message;
